# Generated by Django 6.0 on 2025-12-10 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100)),
                ('numero_turno', models.IntegerField()),
                ('prioridad', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=20)),
                ('hora_estimada', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
