# Generated by Django 6.0 on 2025-12-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueticket',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('ATENDIDO', 'Atendido')], default='PENDIENTE', max_length=20),
        ),
    ]
