# Generated by Django 6.0 on 2025-12-09 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='assigned_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='estimated_time',
            field=models.PositiveIntegerField(),
        ),
    ]
